name: Publish to Powershell gallery
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Release Version
      id: vars
      run: $VERSION=${GITHUB_REF#refs/*/}
    - name: Print version
      run: Write-Output $VERSION
