name: Test action
on: workflow_dispatch

env:
  TEXT: "Hello, World!"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        export FOO=bar
        echo "::set-env name=FOO::$FOO"
    - run: echo $FOO
