name: Publish to Powershell gallery
on: push
env:
  PS_REPOSITORY: github
  GITHUB_FEED: https://nuget.pkg.github.com/BusHero/index.json
  MODULE_MANIFEST: .\src\FontUtilities\FontUtilities.psd1
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: Invoke-Pester .\tests\
    - name: Updated module version
      run: .\update-version.ps1 -Path ${{ env.MODULE_MANIFEST }} -build ${{ github.run_number }}
    - name: Register Github as PSRepository
      run: dotnet nuget add source --username BusHero --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/BusHero/index.json" 
    - name: Create nuspec
      run: .\nuspec.ps1 -ManifestPath .\src\FontUtilities\FontUtilities.psd1
    - name: Pack
      run: nuget pack .\src\FontUtilities\FontUtilities.nuspec
    - name: Load package
      run: dotnet nuget push *.nupkg --source "github" --api-key ${{ secrets.POM }} 
    - name: Upload PowerShell module
      run: Publish-Module -Path . -Exclude '.\github' -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_DEPLOY }}    
