name: Publish to Powershell gallery
on: push
env:
  PS_REPOSITORY: github
  GITHUB_FEED: https://nuget.pkg.github.com/BusHero/index.json
  MODULE_PATH: .\src\FontUtilities\
  MODULE_MANIFEST_PATH: .\src\FontUtilities\FontUtilities.psd1
  NUSPEC_PATH: .\src\FontUtilities\FontUtilities.nuspec
  USERNAME: BusHero
  DOTNET_CLI_TELEMETRY_OPTOUT: true 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: Invoke-Pester .\tests\
    - name: Updated module version
      run: .\update-version.ps1 -Path ${{ env.MODULE_MANIFEST_PATH }} -build ${{ github.run_number }}
    - name: Register Github as PSRepository
      run: dotnet nuget add source --username ${{ env.USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name ${{ env.PS_REPOSITORY }} ${{ env.GITHUB_FEED }}
    - name: Create nuspec
      run: .\nuspec.ps1 -ManifestPath ${{ env.MODULE_MANIFEST_PATH }}
    - name: Pack
      run: nuget pack ${{ env.NUSPEC_PATH }}
    - name: Push package to github 
      run: dotnet nuget push *.nupkg --source ${{ env.PS_REPOSITORY }} --api-key ${{ secrets.POM }}
    - name: Upload package to PSGallery
      run: Publish-Module -Path ${{ env.MODULE_PATH }} -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_DEPLOY }}    
