name: Publish to Powershell gallery
on: push
env:
  PS_REPOSITORY: github
  GITHUB_FEED: https://nuget.pkg.github.com/BusHero/index.json
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Run tests
    #   run: Invoke-Pester .\tests\
    - name: Register Github as PSRepository
      run: Register-PSRepository -Name ${{ env.PS_REPOSITORY }} -SourceLocation ${{ env.GITHUB_FEED }} -PublishLocation ${{ env.GITHUB_FEED }} -InstallationPolicy Trusted
    - name: Show repositories
      run: Get-PSRepository
    # - name: Updated module version
    #   run: |
    #     $version = Test-ModuleManifest .\src\FontUtilities.psd1 | Select-Object -ExpandProperty Version
    #     $version = New-Object System.Version($version.Major, $version.Minor, ${{ github.run_number }})
    #     Update-ModuleManifest .\src\FontUtilities.psd1 -ModuleVersion $version
#     - name: Upload PowerShell module
#       run: Publish-Module -Path . -Exclude '.\github' -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_DEPLOY }}    
