name: Publish to Powershell gallery
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload PowerShell module
      run: Publish-Module -Path . -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_DEPLOY }}    
